name: "01. Manual Workflow"

on:
  workflow_dispatch:

env:
  ELB_APP_NAME_SAMPLE: sample-banking-api
  ELB_ENV_NAME_SAMPLE_PRODUCTION: sample-bank-production-api
  ELB_ENV_NAME_SAMPLE_QA: sample-bank-qa-api

jobs:
  set-account:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set account and version
        id: "account-configuration"
        shell: bash
        run: ./scripts/set-account.sh
    outputs:
      BRANCH: ${{ steps.account-configuration.outputs.BRANCH }}
      ACCOUNT_NAME: ${{ steps.account-configuration.outputs.ACCOUNT_NAME }}
      APP_VERSION: ${{ steps.account-configuration.outputs.APP_VERSION }}

  test:
    runs-on: ubuntu-latest
    needs: set-account
    steps:
      - name: "Logging Configuration"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: |
          echo "------------------------------ Deploy Settings------------------------------ "
          echo Branch: ${{ needs.set-account.outputs.BRANCH }}
          echo Account Name: ${{ needs.set-account.outputs.ACCOUNT_NAME }}
          echo Version: ${{ needs.set-account.outputs.APP_VERSION }}

          echo "------------------------------ AWS Settings------------------------------ "
          echo Beanstalk Application Name: $ELB_APP_NAME_SAMPLE
          echo Beanstalk Environment Name: $ELB_ENV_NAME_SAMPLE_QA
          echo Beanstalk Application Version: ${{ needs.set-account.outputs.APP_VERSION }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: [set-account, test]
    steps:
      - name: "Deploying changes into Production environment"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: "echo Deploy successfully"