name: "01. Automatic Workflow"

on:
  push:
    branches:
      - "rc/*-*"

env:
  APP_VERSION: ${{ github.sha }}

jobs:
  set-account:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set account and version
        if: ${{ github.event_name == 'push' }}
        id: "account-configuration"
        shell: bash
        run: ./scripts/set-account.sh
    outputs:
      BRANCH: ${{ steps.account-configuration.outputs.BRANCH }}
      ACCOUNT_NAME: ${{ steps.account-configuration.outputs.ACCOUNT_NAME }}
      ACCOUNT_NAME_UPPERCASE: ${{ steps.account-configuration.outputs.ACCOUNT_NAME_UPPERCASE }}
      APP_ENV: ${{ steps.account-configuration.outputs.APP_ENV }}

  test:
    runs-on: ubuntu-latest
    needs: set-account
    steps:
      - name: "Logging Configuration"
        shell: bash
        run: |
          echo "------------------------------ Deploy Settings ------------------------------ "
          echo Branch: ${{ needs.set-account.outputs.BRANCH }}
          echo Account Name: ${{ needs.set-account.outputs.ACCOUNT_NAME }}
          echo Env: ${{ needs.set-account.outputs.APP_ENV }}
          echo Build Commit Version: $APP_VERSION
          echo "------------------------------ AWS Settings------------------------------ "
          echo Beanstalk Application Name: "${{ format('sample-bank-{0}-api', needs.set-account.outputs.ACCOUNT_NAME) }}"
          echo Beanstalk Environment Name: "${{ format('sample-bank-{0}-{1}-api', needs.set-account.outputs.ACCOUNT_NAME, needs.set-account.outputs.APP_ENV) }}"
          echo Beanstalk Application Release: $APP_VERSION
  
  deploy:
    runs-on: ubuntu-latest
    needs: [set-account, test]
    steps:
      - name: "Deploying changes"
        shell: bash
        run: "echo Deploy successfully"