name: "01. Manual Workflow"

on:
  workflow_dispatch:

env:
  ACCOUNT_NAME: helloworld
  ELB_APP_NAME_SAMPLE: sample-banking-api
  ELB_ENV_NAME_SAMPLE_PRODUCTION: sample-bank-production-api
  ELB_ENV_NAME_SAMPLE_QA: sample-bank-qa-api

jobs:

  test:
    runs-on: ubuntu-latest
    needs: set-account
    steps:
      - name: "Logging Configuration"
        shell: bash
        run: |
          echo "------------------------------ Deploy Settings------------------------------ "
          echo Branch: ${{ github.ref_name }}
          echo Account Name: $ACCOUNT_NAME
          echo Version: ${{ github.sha }}

          echo "------------------------------ AWS Settings------------------------------ "
          echo Beanstalk Application Name: $ELB_APP_NAME_SAMPLE
          echo Beanstalk Environment Name: $ELB_ENV_NAME_SAMPLE_QA
          echo Beanstalk Application Version: ${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Deploying changes into Production environment"
        shell: bash
        run: "echo Deploy successfully"