name: "01. Manual Workflow"

on:
  workflow_dispatch:

env:
  BRANCH: ${{ github.ref_name }}
  ACCOUNT_NAME: helloworld
  ELB_APP_NAME_SAMPLE: sample-banking-api
  ELB_ENV_NAME_SAMPLE_PRODUCTION: sample-bank-helloworld-production-api
  ELB_ENV_NAME_SAMPLE_QA: sample-bank-helloworld-qa-api
  APP_VERSION: ${{ github.sha }}

jobs:

  test:
    runs-on: ubuntu-latest
    needs: set-account
    steps:
      - name: "Logging Configuration"
        shell: bash
        run: |
        
          echo "------------------------------ Deploy Settings------------------------------ "
          echo Branch: $BRANCH
          echo Account Name: $ACCOUNT_NAME
          echo Version: $APP_VERSION

          echo "------------------------------ AWS Settings------------------------------ "
          echo Beanstalk Application Name: $ELB_APP_NAME_SAMPLE
          echo Beanstalk Environment Name: $ELB_ENV_NAME_SAMPLE_QA
          echo Beanstalk Application Version: $APP_VERSION
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Deploying changes"
        shell: bash
        run: "echo Deploy successfully"