name: "03. Automatic Workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "*"

env:
  REF_NAME: ${{ github.ref_name }}
  REF: ${{ github.ref }}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Logging Configuration"
        shell: bash
        run: |
          echo "------------------------------ Deploy Settings------------------------------ "
          echo Ref Name: $REF_NAME
          echo Ref: $REF
          echo Trigger Name: $GITHUB_EVENT_NAME

      - name: Define Beanstalk Environment Name QA
        run: echo "QA"

      - name: Define Beanstalk Environment Name Production
        run: echo "Production"
        if: contains('refs/tags/v', github.ref)
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Deploying changes"
        shell: bash
        run: "echo Deploy successfully"